include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Поднимаем строгость
    unused_import: error
    unused_local_variable: warning
    dead_code: warning
    missing_required_param: error
    missing_return: error
    invalid_assignment: error
    always_declare_return_types: error
    annotate_overrides: error
    argument_type_not_assignable: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # Общие правила читаемости и чистоты кода
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_locals: true
    always_use_package_imports: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_unnamed_constructors_first: true
    unnecessary_this: true

    # Dart style
    curly_braces_in_flow_control_structures: true
    empty_statements: true
    file_names: true
    slash_for_doc_comments: true
    type_annotate_public_apis: true
    avoid_empty_else: true
    avoid_classes_with_only_static_members: true
    camel_case_types: true
    constant_identifier_names: false

    # Безопасность
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_null_checks_in_equality_operators: true

    # UI и производительность
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true

    # Чистота импорта
    depend_on_referenced_packages: true

    # Nullable safety
    avoid_returning_null_for_future: true
    avoid_returning_null: true
