name: flutter_finances
description: "Flutter pet project from Yandex summer school"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^13.0.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  string_similarity: ^2.0.0
  fl_chart: ^1.0.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1
  dio: ^5.8.0+1
  worker_manager: ^7.2.6
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0
  flutter_gen: ^5.10.0
  flutter_native_splash: ^2.4.6
  drift_dev: ^2.27.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  linux:
    generate: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/icon.png"
  android: true
  ios: true
  android_gravity: center
  fullscreen: true
  color_dark: "#000000"
  image_dark: "assets/icons/icon.png"