name: flutter_finances
description: "Flutter pet project from Yandex summer school"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^13.0.1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  spoiler_widget: ^1.0.12
  sensors_plus: ^4.0.2
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0
  flutter_gen: ^5.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  linux:
    generate: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_gen:
  output: lib/gen/

  integrations:
    image: true
    flutter_svg: true
